---
# Version: 0.2
- name: Comprobar configuracion de servidor SSH
  hosts: all
  become: true
  gather_facts: false
  vars:
    default_ssh_port: 22
    desired_ssh_port: 754
  tasks:
    - name: Comprobar si esta activo puerto 22 por defecto
      delegate_to: localhost
      wait_for:
        port: "{{ default_ssh_port }}"
        host: "{{ ansible_host }}"
        timeout: 10
      ignore_errors: true
      vars:
        ansible_become: false
      register: default_port_check

    - name: Comprobar si esta activo el puerto deseado
      delegate_to: localhost
      wait_for:
        port: "{{ desired_ssh_port }}"
        host: "{{ ansible_host }}"
        timeout: 10
      ignore_errors: true
      vars:
        ansible_become: false
      register: desired_port_check
      
    - fail:
        msg: "ssh is not running (or is running on an unknown port)"
      when: default_port_check is failed and desired_port_check is failed

    - when: default_port_check is success
      block:
        - debug:
            msg: "¡SSH funcionando en el puerto por defecto.!"

    - when: desired_port_check is success
      block:
        - debug:
            msg: "¡SSH funcionando en el puerto deseado.!"
