---
- name: Actualizar repositorio APT
  apt:
    update_cache: true
    cache_valid_time: 3600
  timeout: "{{ os_update_timeout }}"
  changed_when: false
  ignore_errors: true

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: Remove apt lock file 2
  file:
    state: absent
    path: "/var/lib/apt/lists/lock"

- name: Instalar paqueteria basica
  ansible.builtin.apt:
    name:
      - nano
      - ufw
      - curl
      - locales
      - gnupg2
      - ca-certificates 
      - lsb-release 
      - sudo 
      - unzip 
      - bzip2 
      - arj 
      - nomarch 
      - lzop 
      - cabextract 
      - apt-listchanges 
      - git 
      - software-properties-common 
      - net-tools 
      - zip
      - ntp
      - ntpdate
      - python3-pip
      - mc
      - iputils-ping
      - rsyslog
      - openssh-server
      - cron
      - vim-tiny
      - htop
    state: present
  ignore_errors: true



  
